version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./:/app:cached
    command: npx zenn preview
    ports:
      - "8000:8000"
networks:
  default:
    external:
      name: docker_default

